program replace_clipboard_line_breaks
  use, intrinsic            :: iso_c_binding, only: c_ptr, c_funloc, c_null_char
  implicit none

  interface
    function system(command) bind(C, name='system')
      use, intrinsic        :: iso_c_binding, only: c_int, c_char
      integer(c_int)        :: system
      character(kind=c_char), intent(in)    :: command(*)
    end function system
  end interface

  character(len=10000)      :: buffer, line, prev_line
  character(len=100)        :: clipboard_read_cmd, clipboard_write_cmd
  integer                   :: io_status, system_status
  logical                   :: in_code_block, is_empty_line, is_list_item

  ! Determine which clipboard utility to use
  call execute_command_line('which wl-paste > /dev/null 2>&1', exitstat=system_status)
  if (system_status == 0) then
    clipboard_read_cmd = 'wl-paste'
    clipboard_write_cmd = 'wl-copy'
  else
    call execute_command_line('which xsel > /dev/null 2>&1', exitstat=system_status)
    if (system_status == 0) then
      clipboard_read_cmd = 'xsel --clipboard --output'
      clipboard_write_cmd = 'xsel --clipboard --input'
    else
      print *, "Error: Neither wl-clipboard nor xsel found. Please install one of them."
      stop
    end if
  end if

  ! Read from clipboard
  call execute_command_line(trim(clipboard_read_cmd)//' > temp_clipboard.txt', exitstat=system_status)
  if (system_status /= 0) then
    print *, "Error reading from clipboard"
    stop
  end if

  ! Open temporary file
  open(unit=10, file='temp_clipboard.txt', status='old', action='read', iostat=io_status)
  if (io_status /= 0) then
    print *, "Error opening temporary file"
    stop
  end if

  buffer = ""
  prev_line = ""
  in_code_block = .false.
  is_empty_line = .false.

  ! Process the clipboard content line by line
  do
    read(10, '(A)', iostat=io_status) line
    if (io_status /= 0) exit  ! End of file or error

    ! Check if we're entering or leaving a code block
    if (line(1:3) == '```') then
      in_code_block = .not. in_code_block
      if (len_trim(buffer) > 0) buffer = trim(buffer) // char(10)
      buffer = trim(buffer) // trim(line) // char(10)
      cycle
    end if

    ! If in a code block, add the line as-is
    if (in_code_block) then
      buffer = trim(buffer) // trim(line) // char(10)
      cycle
    end if

    ! Check if the current line is empty
    is_empty_line = (len_trim(line) == 0)

    ! Check if the line is a list item (numbered or bullet)
    is_list_item = (line(1:2) == '- ' .or. line(1:2) == '* ' .or. &
                    (line(1:1) >= '0' .and. line(1:1) <= '9' .and. index(line, '.') > 0))

    ! Handle paragraph breaks, list items, and hard line breaks
    if (is_empty_line) then
      ! Empty line, treat as potential paragraph break
      if (len_trim(buffer) > 0 .and. buffer(len_trim(buffer):len_trim(buffer)) /= char(10)) then
        buffer = trim(buffer) // char(10)
      end if
    else if (is_list_item) then
      ! List item, preserve as-is
      if (len_trim(buffer) > 0) buffer = trim(buffer) // char(10)
      buffer = trim(buffer) // trim(line)
    else if (len_trim(prev_line) > 0 .and. .not. is_list_item) then
      ! Hard line break within a paragraph
      buffer = trim(buffer) // ' ' // trim(line)
    else
      ! Start of a new paragraph
      if (len_trim(buffer) > 0) buffer = trim(buffer) // char(10)
      buffer = trim(buffer) // trim(line)
    end if

    prev_line = line
  end do

  ! Close and delete temporary file
  close(10)
  call execute_command_line('rm temp_clipboard.txt', exitstat=system_status)

  ! Write processed content back to clipboard
  open(unit=20, file='temp_output.txt', status='replace', action='write', iostat=io_status)
  if (io_status /= 0) then
    print *, "Error creating temporary output file"
    stop
  end if
  write(20, '(A)') trim(buffer)
  close(20)

  call execute_command_line(trim(clipboard_write_cmd)//' < temp_output.txt', exitstat=system_status)
  if (system_status /= 0) then
    print *, "Error writing to clipboard"
  else
    print *, "Processing complete. Result copied to clipboard."
  end if

  ! Clean up temporary output file
  call execute_command_line('rm temp_output.txt', exitstat=system_status)

end program replace_clipboard_line_breaks

! Say you dictate text using whisper.cpp and proofread that text
! using ollama and llama3. You then copy that text into the linux system clipboard.
! This utility replaces the hard line breaks in the system clipboard
! generated by llama3 in the course of its proofreading of text
! with spaces so that further editing will be normal
!
! wl-clipboard (wayland) or xsel (x11) is assumed to be installed in the linux system
